recipe_sha: 51a33edb249bbe7f0b567e6b5e0d6e6aa27af55c9f3d69af778be26468bb9805  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
category: compiler error
log: |2-
    copying maxentpy/maxent_fast.py -> build/lib.linux-x86_64-cpython-312/maxentpy
    creating build/lib.linux-x86_64-cpython-312/maxentpy/data
    copying maxentpy/data/score3_matrix.txt -> build/lib.linux-x86_64-cpython-312/maxentpy/data
    copying maxentpy/data/matrix5.msg -> build/lib.linux-x86_64-cpython-312/maxentpy/data
    copying maxentpy/data/score5_matrix.txt -> build/lib.linux-x86_64-cpython-312/maxentpy/data
    copying maxentpy/data/matrix3.msg -> build/lib.linux-x86_64-cpython-312/maxentpy/data
    running build_ext
    building 'maxentpy._hashseq' extension
    creating build/temp.linux-x86_64-cpython-312
    creating build/temp.linux-x86_64-cpython-312/maxentpy
    /opt/conda/conda-bld/maxentpy_1718208414735/_build_env/bin/x86_64-conda-linux-gnu-cc -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fPIC -O2 -isystem /opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fdebug-prefix-map=/opt/conda/conda-bld/maxentpy_1718208414735/work=/usr/local/src/conda/maxentpy-0.0.3 -fdebug-prefix-map=/opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -fPIC -I/opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include/python3.12 -c maxentpy/_hashseq.c -o build/temp.linux-x86_64-cpython-312/maxentpy/_hashseq.o
    maxentpy/_hashseq.c:158:12: fatal error: longintrepr.h: No such file or directory
      158 |   #include "longintrepr.h"
          |            ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/opt/conda/conda-bld/maxentpy_1718208414735/_build_env/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
    [1;31merror[0m: [1msubprocess-exited-with-error[0m

    [31m[0m [32mpython setup.py bdist_wheel[0m did not run successfully.
    [31m[0m exit code: [1;36m1[0m
    [31m>[0m See above for output.

    [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
    [1;35mfull command[0m: [34m/opt/conda/conda-bld/maxentpy_1718208414735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python -u -c '[0m
  [34m  exec(compile('"'"''"'"''"'"'[0m
  [34m  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py[0m
  [34m  #[0m
  [34m  # - It imports setuptools before invoking setup.py, to enable projects that directly[0m
  [34m  #   import from distutils.core to work with newer packaging standards.[0m
  [34m  # - It provides a clear error message when setuptools is not installed.[0m
  [34m  # - It sets sys.argv[0] to the underlying setup.py, when invoking setup.py so[0m
  [34m  #   setuptools doesn'"'"'t think the script is -c. This avoids the following warning:[0m
  [34m  #     manifest_maker: standard file '"'"'-c'"'"' not found".[0m
  [34m  # - It generates a shim setup.py, for handling setup.cfg-only projects.[0m
  [34m  import os, sys, tokenize[0m
  [34m  [0m
  [34m  try:[0m
  [34m      import setuptools[0m
  [34m  except ImportError as error:[0m
  [34m      print([0m
  [34m          "ERROR: Can not execute setup.py since setuptools is not available in "[0m
  [34m          "the build environment.",[0m
  [34m          file=sys.stderr,[0m
  [34m      )[0m
  [34m      sys.exit(1)[0m
  [34m  [0m
  [34m  __file__ = %r[0m
  [34m  sys.argv[0] = __file__[0m
  [34m  [0m
  [34m  if os.path.exists(__file__):[0m
  [34m      filename = __file__[0m
  [34m      with tokenize.open(__file__) as f:[0m
  [34m          setup_py_code = f.read()[0m
  [34m  else:[0m
  [34m      filename = "<auto-generated setuptools caller>"[0m
  [34m      setup_py_code = "from setuptools import setup; setup()"[0m
  [34m  [0m
  [34m  exec(compile(setup_py_code, filename, "exec"))[0m
  [34m  '"'"''"'"''"'"' % ('"'"'/opt/conda/conda-bld/maxentpy_1718208414735/work/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /tmp/pip-wheel-8izlri85[0m
    [1;35mcwd[0m: /opt/conda/conda-bld/maxentpy_1718208414735/work/
    Building wheel for maxentpy (setup.py): finished with status 'error'
  [31m  ERROR: Failed building wheel for maxentpy[0m[31m
  [0m  Running setup.py clean for maxentpy
    Running command python setup.py clean
    running clean
    removing 'build/temp.linux-x86_64-cpython-312' (and everything under it)
    removing 'build/lib.linux-x86_64-cpython-312' (and everything under it)
    'build/bdist.linux-x86_64' does not exist -- can't clean it
    'build/scripts-3.12' does not exist -- can't clean it
    removing 'build'
  [31mERROR: Could not build wheels for maxentpy, which is required to install pyproject.toml-based projects[0m[31m
  [0mFailed to build maxentpy
  Exception information:
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
      status = run_func(*args)
               ^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
      return func(self, options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 429, in run
      raise InstallationError(
  pip._internal.exceptions.InstallationError: Could not build wheels for maxentpy, which is required to install pyproject.toml-based projects
  Removed build tracker: '/tmp/pip-build-tracker-mlxbh6c4'
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/maxentpy_1718208414735/work/conda_build.sh']' returned non-zero exit status 1.
# Last 100 lines of the build log.
