recipe_sha: f3f2c1bbefdf1e99911e0d1d4f403990baeeedf254257d438ed54d1d17df8c3c  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
        self.run_command("build")
      File "/opt/conda/conda-bld/flye_1734064796862/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/conda-bld/flye_1734064796862/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
        super().run_command(command)
      File "/opt/conda/conda-bld/flye_1734064796862/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/opt/conda/conda-bld/flye_1734064796862/work/setup.py", line 40, in run
        sys.exit("Compilation error: ", e)
    TypeError: exit expected at most 1 argument, got 2
    [1;31merror[0m: [1msubprocess-exited-with-error[0m

    [31m[0m [32mpython setup.py bdist_wheel[0m did not run successfully.
    [31m[0m exit code: [1;36m1[0m
    [31m>[0m See above for output.

    [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
    [1;35mfull command[0m: [34m/opt/conda/conda-bld/flye_1734064796862/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python -u -c '[0m
  [34m  exec(compile('"'"''"'"''"'"'[0m
  [34m  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py[0m
  [34m  #[0m
  [34m  # - It imports setuptools before invoking setup.py, to enable projects that directly[0m
  [34m  #   import from distutils.core to work with newer packaging standards.[0m
  [34m  # - It provides a clear error message when setuptools is not installed.[0m
  [34m  # - It sets sys.argv[0] to the underlying setup.py, when invoking setup.py so[0m
  [34m  #   setuptools doesn'"'"'t think the script is -c. This avoids the following warning:[0m
  [34m  #     manifest_maker: standard file '"'"'-c'"'"' not found".[0m
  [34m  # - It generates a shim setup.py, for handling setup.cfg-only projects.[0m
  [34m  import os, sys, tokenize[0m
  [34m  [0m
  [34m  try:[0m
  [34m      import setuptools[0m
  [34m  except ImportError as error:[0m
  [34m      print([0m
  [34m          "ERROR: Can not execute setup.py since setuptools is not available in "[0m
  [34m          "the build environment.",[0m
  [34m          file=sys.stderr,[0m
  [34m      )[0m
  [34m      sys.exit(1)[0m
  [34m  [0m
  [34m  __file__ = %r[0m
  [34m  sys.argv[0] = __file__[0m
  [34m  [0m
  [34m  if os.path.exists(__file__):[0m
  [34m      filename = __file__[0m
  [34m      with tokenize.open(__file__) as f:[0m
  [34m          setup_py_code = f.read()[0m
  [34m  else:[0m
  [34m      filename = "<auto-generated setuptools caller>"[0m
  [34m      setup_py_code = "from setuptools import setup; setup()"[0m
  [34m  [0m
  [34m  exec(compile(setup_py_code, filename, "exec"))[0m
  [34m  '"'"''"'"''"'"' % ('"'"'/opt/conda/conda-bld/flye_1734064796862/work/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /tmp/pip-wheel-e7rp0hk7[0m
    [1;35mcwd[0m: /opt/conda/conda-bld/flye_1734064796862/work/
    Building wheel for flye (setup.py): finished with status 'error'
  [31m  ERROR: Failed building wheel for flye[0m[31m
  [0m  Running setup.py clean for flye
    Running command python setup.py clean
    running clean
    removing 'build/lib' (and everything under it)
    'build/bdist.linux-x86_64' does not exist -- can't clean it
    'build/scripts-3.10' does not exist -- can't clean it
    removing 'build'
  Failed to build flye
  [31mERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flye)[0m[31m
  [0mException information:
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
      status = _inner_run()
    File "$PREFIX/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
      return self.run(options, args)
    File "$PREFIX/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
      return func(self, options, args)
    File "$PREFIX/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 434, in run
      raise InstallationError(
  pip._internal.exceptions.InstallationError: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flye)
  Removed build tracker: '/tmp/pip-build-tracker-5fyqno6c'
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/flye_1734064796862/work/conda_build.sh']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
      raise BuildScriptException(str(exc), caused_by=exc) from exc
  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/flye_1734064796862/work/conda_build.sh']' returned non-zero exit status 1.
# Last 100 lines of the build log.
