recipe_sha: 818b19264e031ab0aafc69a65856602ab4de67b68aed3fe7e3117d898e0765f6  # The commit at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |2-
      pip:              23.1.2-pyhd8ed1ab_0        conda-forge
      python:           3.10.11-he550d4f_0_cpython conda-forge
      readline:         8.2-h8228510_1             conda-forge
      setuptools:       67.7.2-pyhd8ed1ab_0        conda-forge
      tk:               8.6.12-h27826a3_0          conda-forge
      tzdata:           2023c-h71feb2d_0           conda-forge
      wheel:            0.40.0-pyhd8ed1ab_0        conda-forge
      xz:               5.2.6-h166bdaf_0           conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  [34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0G[] 0.0s
  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                         1.5kB @  11.4MB/s  0.0s
  opt/conda/conda-bld/noarch                         127.0 B @   2.6MB/s  0.0s
  [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
  [?25l[2K[0Gopt/conda/conda-bld/linux-64                         1.5kB @  19.5MB/s  0.0s
  opt/conda/conda-bld/noarch                         127.0 B @   3.3MB/s  0.0s
  [?25hMamba failed to solve:
   - python_abi 3.10.* *_cp310
   - numpy
   - python >=3.10,<3.11.0a0
   - scipy
   - pysam
   - bedtools
   - matplotlib 3.3.*
   - samtools

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package matplotlib-3.3.2-h06a4308_0 requires matplotlib-base >=3.3.2,<3.3.3.0a0, but none of the providers can be installed
  -

  Leaving build/test directories:
    Work:
   /opt/conda/conda-bld/work
    Test:
   /opt/conda/conda-bld/test_tmp
  Leaving build/test environments:
    Test:
  source activate  /opt/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
    Build:
  source activate  /opt/conda/conda-bld/_build_env


  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
      solution = solver.solve_for_action(_specs, prefix)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 230, in solve_for_action
      t = self.solve(specs)
    File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 220, in solve
      raise RuntimeError("Solver could not find solution."  error_string)
  RuntimeError: Solver could not find solution.Mamba failed to solve:
   - python_abi 3.10.* *_cp310
   - numpy
   - python >=3.10,<3.11.0a0
   - scipy
   - pysam
   - bedtools
   - matplotlib 3.3.*
   - samtools

  with channels:
   - conda-forge
   - bioconda
   - defaults

  The reported errors are:
  - Encountered problems while solving:
  -   - package matplotlib-3.3.2-h06a4308_0 requires matplotlib-base >=3.3.2,<3.3.3.0a0, but none of the providers can be installed
  -

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
      call_conda_build(action, config)
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
      result = api.build(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
      return build_tree(
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
      packages_from_this = build(metadata, stats,
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2115, in build
      create_build_envs(top_level_pkg, notest)
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1993, in create_build_envs
      raise e
    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1972, in create_build_envs
      environ.get_install_actions(m.config.test_prefix,
    File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 150, in mamba_get_install_actions
      raise err
  conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("matplotlib==3.3.2=h06a4308_0"), MatchSpec("matplotlib-base[version='>=3.3.2,<3.3.3.0a0']")}
# Last 100 lines of the build log.
