recipe_sha: 0c3fb5d570dc4b66dc35de9ba850a12bc8cf40c159b78490d6fc3af5302176ca  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
category: test failure
log: |-
  usage: faithpd -i <biom> -t <newick> -o <out.txt>

      -i		The input BIOM table.
      -t		The input phylogeny in newick.
      -o		The output series.

  Citations:
      For Faith's PD, please see:
          Faith Biological Conservation 1992; DOI: 10.1016/0006-3207(92)91201-3

   python -m unittest unifrac.tests.test_methods
  .........
  ----------------------------------------------------------------------
  Ran 9 tests in 0.018s

  OK
   python -m unittest unifrac.tests.test_api
  ....................................EEEE
  ======================================================================
  ERROR: test_unweighted_fp32_inmem (unifrac.tests.test_api.UnifracAPITests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 137, in _get_phylogenetic_kwargs
      taxa = kwargs.pop("taxa")
  KeyError: 'taxa'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/unifrac/tests/test_api.py", line 59, in test_unweighted_fp32_inmem
      exp = skbio.diversity.beta_diversity('unweighted_unifrac', cnts,
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_driver.py", line 439, in beta_diversity
      taxa, tree, kwargs = _get_phylogenetic_kwargs(counts, **kwargs)
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 139, in _get_phylogenetic_kwargs
      raise ValueError("taxa is required for phylogenetic diversity " "metrics.")
  ValueError: taxa is required for phylogenetic diversity metrics.

  ======================================================================
  ERROR: test_unweighted_fp64_inmem (unifrac.tests.test_api.UnifracAPITests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 137, in _get_phylogenetic_kwargs
      taxa = kwargs.pop("taxa")
  KeyError: 'taxa'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/unifrac/tests/test_api.py", line 79, in test_unweighted_fp64_inmem
      exp = skbio.diversity.beta_diversity('unweighted_unifrac', cnts,
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_driver.py", line 439, in beta_diversity
      taxa, tree, kwargs = _get_phylogenetic_kwargs(counts, **kwargs)
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 139, in _get_phylogenetic_kwargs
      raise ValueError("taxa is required for phylogenetic diversity " "metrics.")
  ValueError: taxa is required for phylogenetic diversity metrics.

  ======================================================================
  ERROR: test_unweighted_inmem (unifrac.tests.test_api.UnifracAPITests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 137, in _get_phylogenetic_kwargs
      taxa = kwargs.pop("taxa")
  KeyError: 'taxa'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/unifrac/tests/test_api.py", line 39, in test_unweighted_inmem
      exp = skbio.diversity.beta_diversity('unweighted_unifrac', cnts,
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_driver.py", line 439, in beta_diversity
      taxa, tree, kwargs = _get_phylogenetic_kwargs(counts, **kwargs)
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 139, in _get_phylogenetic_kwargs
      raise ValueError("taxa is required for phylogenetic diversity " "metrics.")
  ValueError: taxa is required for phylogenetic diversity metrics.

  ======================================================================
  ERROR: test_unweighted_root_eval_issue_46 (unifrac.tests.test_api.UnifracAPITests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 137, in _get_phylogenetic_kwargs
      taxa = kwargs.pop("taxa")
  KeyError: 'taxa'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/unifrac/tests/test_api.py", line 104, in test_unweighted_root_eval_issue_46
      exp = skbio.diversity.beta_diversity('unweighted_unifrac', cnts,
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_driver.py", line 439, in beta_diversity
      taxa, tree, kwargs = _get_phylogenetic_kwargs(counts, **kwargs)
    File "/opt/conda/conda-bld/unifrac_1717780005364/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/skbio/diversity/_util.py", line 139, in _get_phylogenetic_kwargs
      raise ValueError("taxa is required for phylogenetic diversity " "metrics.")
  ValueError: taxa is required for phylogenetic diversity metrics.

  ----------------------------------------------------------------------
  Ran 40 tests in 3.379s

  FAILED (errors=4)
  WARNING: Tests failed for unifrac-1.3-py38h0020b31_1.tar.bz2 - moving package to /opt/conda/conda-bld/broken
  TESTS FAILED: unifrac-1.3-py38h0020b31_1.tar.bz2
# Last 100 lines of the build log.
