recipe_sha: 4af3647b9bfd656d9bd240430c97beda5ef5bb1a2af01a13f2518974f451e4b8  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  SIZE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-size
  STRINGS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strings
  STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip
  INFO: activate-gcc_linux-64.sh made the following environmental changes:
  BUILD=x86_64-conda-linux-gnu
  CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
  CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pxblat-1.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
  CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
  CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pxblat-1.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
  HOST=x86_64-conda-linux-gnu
  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
  MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib
  _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
  build_alias=x86_64-conda-linux-gnu
  host_alias=x86_64-conda-linux-gnu
  -BUILD=x86_64-conda_cos6-linux-gnu
  -CONDA_BUILD_SYSROOT=
  INFO: activate-gxx_linux-64.sh made the following environmental changes:
  CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pxblat-1.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pxblat-1.2.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
  GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
  Using pip 24.0 from $PREFIX/lib/python3.12/site-packages/pip (python 3.12)
  Non-user install because user site-packages disabled
  Ignoring indexes: https://pypi.org/simple
  Created temporary directory: /tmp/pip-build-tracker-wnlce67n
  Initialized build tracking at /tmp/pip-build-tracker-wnlce67n
  Created build tracker: /tmp/pip-build-tracker-wnlce67n
  Entered build tracker: /tmp/pip-build-tracker-wnlce67n
  Created temporary directory: /tmp/pip-install-jujpp588
  Created temporary directory: /tmp/pip-ephem-wheel-cache-s12l4w7q
  Processing $SRC_DIR
    Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-wnlce67n'
    Created temporary directory: /tmp/pip-modern-metadata-83qnmnky
    Preparing metadata (pyproject.toml): started
    Running command Preparing metadata (pyproject.toml)
    Preparing metadata (pyproject.toml): finished with status 'done'
    Source in $SRC_DIR has version 1.2.1, which satisfies requirement pxblat==1.2.1 from file://$SRC_DIR
    Removed pxblat==1.2.1 from file://$SRC_DIR from build tracker '/tmp/pip-build-tracker-wnlce67n'
  INFO: pip is looking at multiple versions of pxblat to determine which version is compatible with other requirements. This could take a while.
  Will try a different candidate, due to conflict:
      pxblat 1.2.1 depends on Python <3.12,>=3.9
  [31mERROR: Package 'pxblat' requires a different Python: 3.12.3 not in '<3.12,>=3.9'[0m[31m
  [0mException information:
  Traceback (most recent call last):
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
      result = self._result = resolver.resolve(
                              ^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
      raise ResolutionImpossible(self.state.backtrack_causes)
  pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=RequiresPythonRequirement('<3.12,>=3.9'), parent=LinkCandidate('file://$SRC_DIR'))]

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
      status = run_func(*args)
               ^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
      return func(self, options, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
      requirement_set = resolver.resolve(
                        ^^^^^^^^^^^^^^^^^
    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
      raise error from e
  pip._internal.exceptions.UnsupportedPythonVersion: Package 'pxblat' requires a different Python: 3.12.3 not in '<3.12,>=3.9'
  Removed build tracker: '/tmp/pip-build-tracker-wnlce67n'
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
      utils.check_call_env(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/pxblat_1717553732618/work/conda_build.sh']' returned non-zero exit status 1.
# Last 100 lines of the build log.
