recipe_sha: 8cb84db6d99035c207fba55e0fe0ed8578b4bf22050b93e8e48aeabcfe0ccea1  # The hash of the recipe's meta.yaml at which this recipe failed to build.
skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
log: |-
  2024-12-15T20:08:51 noarch Applying patch instructions
  2024-12-15T20:08:51 noarch Writing patched repodata
  2024-12-15T20:08:51 noarch Building current_repodata subset
  2024-12-15T20:08:51 noarch Writing current_repodata subset
  2024-12-15T20:08:51 noarch Writing index HTML
  /opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py:501: UserWarning: RECIPE_PATH received is a file (/opt/recipe/meta.yaml).
  It should be a path to a folder.
  Forcing conda-build to use the recipe file.
    warnings.warn(
  WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
  Adding in variants from internal_defaults
  Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
  Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
  Attempting to finalize metadata for snap
  Reloading output folder: ...working... done
  Getting pinned dependencies: ...working... done
  Reloading output folder: ...working... done
  Getting pinned dependencies: ...working... done
  BUILD START: ['snap-2013_11_29-h7b50bb2_7.tar.bz2']
  Reloading output folder: ...working... done
  Solving environment (_h_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/snap_1734293332575/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol


  The following NEW packages will be INSTALLED:

      _libgcc_mutex: 0.1-conda_forge   conda-forge
      _openmp_mutex: 4.5-2_gnu         conda-forge
      libgcc:        14.2.0-h77fa898_1 conda-forge
      libgomp:       14.2.0-h77fa898_1 conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  Reloading output folder: ...working... done
  Solving environment (_build_env): ...working... done
  Reloading output folder: ...working... done
  Solving environment (_test_env): ...working... done

  ## Package Plan ##

    environment location: /opt/conda/conda-bld/snap_1734293332575/_build_env


  The following NEW packages will be INSTALLED:

      _libgcc_mutex:           0.1-conda_forge     conda-forge
      _openmp_mutex:           4.5-2_gnu           conda-forge
      binutils_impl_linux-64:  2.43-h4bf12b8_2     conda-forge
      binutils_linux-64:       2.43-h4852527_2     conda-forge
      gcc_impl_linux-64:       13.3.0-hfea6d02_1   conda-forge
      gcc_linux-64:            13.3.0-hc28eda2_7   conda-forge
      kernel-headers_linux-64: 3.10.0-he073ed8_18  conda-forge
      ld_impl_linux-64:        2.43-h712a8e2_2     conda-forge
      libgcc:                  14.2.0-h77fa898_1   conda-forge
      libgcc-devel_linux-64:   13.3.0-h84ea5a7_101 conda-forge
      libgomp:                 14.2.0-h77fa898_1   conda-forge
      libsanitizer:            13.3.0-heb74ff8_1   conda-forge
      libstdcxx:               14.2.0-hc0a3c3a_1   conda-forge
      make:                    4.4.1-hb9d3cd8_2    conda-forge
      sysroot_linux-64:        2.17-h4a8ded7_18    conda-forge
      tzdata:                  2024b-hc8b5060_0    conda-forge

  Preparing transaction: ...working... done
  Verifying transaction: ...working... done
  Executing transaction: ...working... done
  Source cache directory is: /opt/conda/conda-bld/src_cache
  Downloading source to cache: snap-2013-11-29_e2a236392d.tar.gz
  Downloading http://korflab.ucdavis.edu/Software/snap-2013-11-29.tar.gz
  WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f102214e920>, 'Connection to korflab.ucdavis.edu timed out. (connect timeout=9.15)')': /Software/snap-2013-11-29.tar.gz
  WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f102214e9e0>, 'Connection to korflab.ucdavis.edu timed out. (connect timeout=9.15)')': /Software/snap-2013-11-29.tar.gz
  WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f102214eb60>, 'Connection to korflab.ucdavis.edu timed out. (connect timeout=9.15)')': /Software/snap-2013-11-29.tar.gz
  WARNING: Error: HTTP 000 CONNECTION FAILED for url <http://korflab.ucdavis.edu/Software/snap-2013-11-29.tar.gz>
  Elapsed: -

  An HTTP error occurred when trying to retrieve this URL.
  HTTP errors are often intermittent, and a simple retry will get you on your way.
  Traceback (most recent call last):
    File "/opt/conda/bin/conda-build", line 11, in <module>
      sys.exit(execute())
    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
      api.build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
      return build_tree(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
      packages_from_this = build(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2449, in build
      try_download(m, no_download_source=False, raise_error=True)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 762, in try_download
      source.provide(metadata)
    File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 1035, in provide
      unpack(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 169, in unpack
      src_path, unhashed_fn = download_to_cache(
    File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 116, in download_to_cache
      raise RuntimeError(f"Could not download {url}")
  RuntimeError: Could not download http://korflab.ucdavis.edu/Software/snap-2013-11-29.tar.gz
# Last 100 lines of the build log.
category: |-
  source download error
